apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcs-trigger
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcs-trigger
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcs-trigger
subjects:
  - kind: ServiceAccount
    name: vcs-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vcs-trigger
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  params:
    - name: source-repo
      description: Source code repository
    - name: sha
      description: Precise SHA of the commit to build
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: next-js-sample-app-pipeline-
      spec:
        pipelineRef:
          name: nodejs-pipeline
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: next-js-sample-app
          - name: source-repo
            value: $(tt.params.source-repo)  # use value from trigger event
          - name: sha                        # introduce new param
            value: $(tt.params.sha)          # use value from trigger event
          - name: image-repo
            value: quay.io/samchinellato/next-js-sample-app
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi


